version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'db_logistics' 
      POSTGRES_USER: 'admin' 
      POSTGRES_PASSWORD: '12345'
    ports:
      - "5432:5432"
  web:
    build: .
    command:
      sh -c "/wait-for-it.sh db:5432 -- python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py initialize_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

